// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  deleteAccount,
  deleteAccountCategory,
  deleteAccountSubcategory,
  deletePaymentTerm,
  getAccount,
  getAccounts,
  getAccountsList,
  getAccountCategories,
  getAccountCategoriesList,
  getAccountCategory,
  getAccountSubcategories,
  getAccountSubcategoriesByCategory,
  getAccountSubcategory,
  getBaseCurrency,
  getChartOfAccounts,
  getCurrency,
  getCurrencyByCode,
  getCurrencies,
  getCurrenciesList,
  getCurrentAccountingPeriod,
  getDefaultAccounts,
  getFiscalYearSettings,
  getInventoryPostingGroup,
  getInventoryPostingGroups,
  getPaymentTerm,
  getPaymentTerms,
  getPaymentTermsList,
  getPurchasingPostingGroup,
  getPurchasingPostingGroups,
  getPurchasingSalesGroup,
  getSalesPostingGroups,
  updateDefaultBalanceSheetAccounts,
  updateDefaultIncomeAccounts,
  updateFiscalYearSettings,
  upsertAccount,
  upsertAccountCategory,
  upsertAccountSubcategory,
  upsertCurrency,
  upsertPaymentTerm,
} from "~/modules/accounting/accounting.service";
import {
  defaultBalanceSheetAccountValidator,
  defaultIncomeAcountValidator,
  fiscalYearSettingsValidator,
  accountValidator,
  accountCategoryValidator,
  accountSubcategoryValidator,
  currencyValidator,
  paymentTermValidator,
} from "~/modules/accounting/accounting.models";

export const registerAccountingTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "accounting_deleteAccount",
    {
      description: "delete account",
      inputSchema: {
      accountId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccount(ctx.client, params.accountId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccount"),
  );

  server.registerTool(
    "accounting_deleteAccountCategory",
    {
      description: "delete account category",
      inputSchema: {
      accountCategoryId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccountCategory(ctx.client, params.accountCategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccountCategory"),
  );

  server.registerTool(
    "accounting_deleteAccountSubcategory",
    {
      description: "delete account subcategory",
      inputSchema: {
      accountSubcategoryId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteAccountSubcategory(ctx.client, params.accountSubcategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_deleteAccountSubcategory"),
  );

  server.registerTool(
    "accounting_deletePaymentTerm",
    {
      description: "delete payment term",
      inputSchema: {
      paymentTermId: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePaymentTerm(ctx.client, params.paymentTermId);
      return toMcpResult(result);
    }, "Failed: accounting_deletePaymentTerm"),
  );

  server.registerTool(
    "accounting_getAccount",
    {
      description: "get account",
      inputSchema: {
      accountId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccount(ctx.client, params.accountId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccount"),
  );

  server.registerTool(
    "accounting_getAccounts",
    {
      description: "get accounts",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccounts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccounts"),
  );

  server.registerTool(
    "accounting_getAccountsList",
    {
      description: "get accounts list",
      inputSchema: {
      args: z.object({
    type: z.any().optional(),
    incomeBalance: z.any().optional(),
    classes: z.array(z.any()).optional()
  }).optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountsList(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountsList"),
  );

  server.registerTool(
    "accounting_getAccountCategories",
    {
      description: "get account categories",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountCategories(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategories"),
  );

  server.registerTool(
    "accounting_getAccountCategoriesList",
    {
      description: "get account categories list",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountCategoriesList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategoriesList"),
  );

  server.registerTool(
    "accounting_getAccountCategory",
    {
      description: "get account category",
      inputSchema: {
      accountCategoryId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountCategory(ctx.client, params.accountCategoryId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountCategory"),
  );

  server.registerTool(
    "accounting_getAccountSubcategories",
    {
      description: "get account subcategories",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategories(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategories"),
  );

  server.registerTool(
    "accounting_getAccountSubcategoriesByCategory",
    {
      description: "get account subcategories by category",
      inputSchema: {
      accountCategoryId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategoriesByCategory(ctx.client, params.accountCategoryId, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategoriesByCategory"),
  );

  server.registerTool(
    "accounting_getAccountSubcategory",
    {
      description: "get account subcategory",
      inputSchema: {
      accountSubcategoryId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountSubcategory(ctx.client, params.accountSubcategoryId);
      return toMcpResult(result);
    }, "Failed: accounting_getAccountSubcategory"),
  );

  server.registerTool(
    "accounting_getBaseCurrency",
    {
      description: "get base currency",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getBaseCurrency(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getBaseCurrency"),
  );

  server.registerTool(
    "accounting_getChartOfAccounts",
    {
      description: "get chart of accounts",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    name: z.string().nullable(),
    incomeBalance: z.enum(["Income Statement", "Balance Sheet", "null"]),
    startDate: z.string().nullable(),
    endDate: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getChartOfAccounts(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getChartOfAccounts"),
  );

  server.registerTool(
    "accounting_getCurrency",
    {
      description: "get currency",
      inputSchema: {
      currencyId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrency(ctx.client, params.currencyId);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrency"),
  );

  server.registerTool(
    "accounting_getCurrencyByCode",
    {
      description: "get currency by code",
      inputSchema: {
      currencyCode: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrencyByCode(ctx.client, ctx.companyId, params.currencyCode);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrencyByCode"),
  );

  server.registerTool(
    "accounting_getCurrencies",
    {
      description: "get currencies",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrencies(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrencies"),
  );

  server.registerTool(
    "accounting_getCurrenciesList",
    {
      description: "get currencies list",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrenciesList(ctx.client);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrenciesList"),
  );

  server.registerTool(
    "accounting_getCurrentAccountingPeriod",
    {
      description: "get current accounting period",
      inputSchema: {
      date: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrentAccountingPeriod(ctx.client, ctx.companyId, params.date);
      return toMcpResult(result);
    }, "Failed: accounting_getCurrentAccountingPeriod"),
  );

  server.registerTool(
    "accounting_getDefaultAccounts",
    {
      description: "get default accounts",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getDefaultAccounts(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getDefaultAccounts"),
  );

  server.registerTool(
    "accounting_getFiscalYearSettings",
    {
      description: "get fiscal year settings",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getFiscalYearSettings(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getFiscalYearSettings"),
  );

  server.registerTool(
    "accounting_getInventoryPostingGroup",
    {
      description: "get inventory posting group",
      inputSchema: {
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    locationId: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryPostingGroup(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getInventoryPostingGroup"),
  );

  server.registerTool(
    "accounting_getInventoryPostingGroups",
    {
      description: "get inventory posting groups",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getInventoryPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getInventoryPostingGroups"),
  );

  server.registerTool(
    "accounting_getPaymentTerm",
    {
      description: "get payment term",
      inputSchema: {
      paymentTermId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTerm(ctx.client, params.paymentTermId);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTerm"),
  );

  server.registerTool(
    "accounting_getPaymentTerms",
    {
      description: "get payment terms",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTerms(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTerms"),
  );

  server.registerTool(
    "accounting_getPaymentTermsList",
    {
      description: "get payment terms list",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPaymentTermsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: accounting_getPaymentTermsList"),
  );

  server.registerTool(
    "accounting_getPurchasingPostingGroup",
    {
      description: "get purchasing posting group",
      inputSchema: {
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    supplierTypeId: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingPostingGroup(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingPostingGroup"),
  );

  server.registerTool(
    "accounting_getPurchasingPostingGroups",
    {
      description: "get purchasing posting groups",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingPostingGroups"),
  );

  server.registerTool(
    "accounting_getPurchasingSalesGroup",
    {
      description: "get purchasing sales group",
      inputSchema: {
      args: z.object({
    itemPostingGroupId: z.string().nullable(),
    customerTypeId: z.string().nullable()
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPurchasingSalesGroup(ctx.client, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getPurchasingSalesGroup"),
  );

  server.registerTool(
    "accounting_getSalesPostingGroups",
    {
      description: "get sales posting groups",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0)
  }),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesPostingGroups(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: accounting_getSalesPostingGroups"),
  );

  server.registerTool(
    "accounting_updateDefaultBalanceSheetAccounts",
    {
      description: "update default balance sheet accounts",
      inputSchema: {
      defaultAccounts: defaultBalanceSheetAccountValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultBalanceSheetAccounts(ctx.client, { ...params.defaultAccounts, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateDefaultBalanceSheetAccounts"),
  );

  server.registerTool(
    "accounting_updateDefaultIncomeAccounts",
    {
      description: "update default income accounts",
      inputSchema: {
      defaultAccounts: defaultIncomeAcountValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultIncomeAccounts(ctx.client, { ...params.defaultAccounts, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateDefaultIncomeAccounts"),
  );

  server.registerTool(
    "accounting_updateFiscalYearSettings",
    {
      description: "update fiscal year settings",
      inputSchema: {
      fiscalYearSettings: fiscalYearSettingsValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateFiscalYearSettings(ctx.client, { ...params.fiscalYearSettings, companyId: ctx.companyId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_updateFiscalYearSettings"),
  );

  server.registerTool(
    "accounting_upsertAccount",
    {
      description: "upsert account",
      inputSchema: {
      account: accountValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccount(ctx.client, { ...params.account, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccount"),
  );

  server.registerTool(
    "accounting_upsertAccountCategory",
    {
      description: "upsert account category",
      inputSchema: {
      accountCategory: accountCategoryValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccountCategory(ctx.client, { ...params.accountCategory, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccountCategory"),
  );

  server.registerTool(
    "accounting_upsertAccountSubcategory",
    {
      description: "upsert account subcategory",
      inputSchema: {
      accountSubcategory: accountSubcategoryValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertAccountSubcategory(ctx.client, { ...params.accountSubcategory, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertAccountSubcategory"),
  );

  server.registerTool(
    "accounting_upsertCurrency",
    {
      description: "upsert currency",
      inputSchema: {
      currency: currencyValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertCurrency(ctx.client, { ...params.currency, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertCurrency"),
  );

  server.registerTool(
    "accounting_upsertPaymentTerm",
    {
      description: "upsert payment term",
      inputSchema: {
      paymentTerm: paymentTermValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPaymentTerm(ctx.client, { ...params.paymentTerm, companyId: ctx.companyId, createdBy: ctx.userId, updatedBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: accounting_upsertPaymentTerm"),
  );
};
