// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  getAccountsPayableBillingAddress,
  getAccountsReceivableBillingAddress,
  updateAccountsPayableBillingAddress,
  updateAccountsReceivableBillingAddress,
  deleteApiKey,
  deleteWebhook,
  deactivateWebhooks,
  getApiKeys,
  getCompanies,
  getCompany,
  getCompanyPlan,
  getCompanySettings,
  getCompanyIntegrations,
  getConfig,
  getCurrentSequence,
  getCustomField,
  getCustomFields,
  getCustomFieldsTables,
  getIntegration,
  getIntegrations,
  getKanbanOutputSetting,
  getPlanById,
  getPlans,
  getNextSequence,
  getSequence,
  getSequences,
  getSequencesList,
  getTerms,
  getWebhook,
  getWebhookTables,
  getWebhooks,
  insertCompany,
  updateCompanyPlan,
  seedCompany,
  updateCompany,
  updateKanbanOutputSetting,
  updateMetricSettings,
  upsertApiKey,
  updateDigitalQuoteSetting,
  updateLogoDark,
  updateLogoLight,
  updateLogoDarkIcon,
  updateLogoLightIcon,
  updateMaterialGeneratedIdsSetting,
  updateMaterialUnitsSetting,
  updateProductLabelSize,
  updatePurchasingPdfThumbnails,
  updateSalesPdfThumbnails,
  updateJobTravelerWorkInstructions,
  updateTimeCardSetting,
  updateConsoleSetting,
  updateRfqReadySetting,
  updateSuggestionNotificationSetting,
  updateMaintenanceDispatchNotificationSettings,
  updateSupplierQuoteNotificationSetting,
  updatePurchasePriceUpdateTimingSetting,
  updateLeadTimesOnReceiptSetting,
  updateSupplierApprovalSetting,
  updateAccountsPayableAddressSetting,
  updateAccountsReceivableAddressSetting,
  updateAccountsPayableEmail,
  updateAccountsReceivableEmail,
  updateDefaultSupplierCc,
  updateDefaultCustomerCc,
  updateQuoteLineCategoryMarkups,
  updateSequence,
  updateIntegrationMetadata,
  upsertWebhook,
} from "~/modules/settings/settings.service";
import {
  accountsPayableBillingAddressValidator,
  accountsReceivableBillingAddressValidator,
  companyValidator,
  apiKeyValidator,
  sequenceValidator,
  webhookValidator,
} from "~/modules/settings/settings.models";

export const registerSettingsTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "settings_getAccountsPayableBillingAddress",
    {
      description: "get accounts payable billing address",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountsPayableBillingAddress(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getAccountsPayableBillingAddress"),
  );

  server.registerTool(
    "settings_getAccountsReceivableBillingAddress",
    {
      description: "get accounts receivable billing address",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getAccountsReceivableBillingAddress(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getAccountsReceivableBillingAddress"),
  );

  server.registerTool(
    "settings_updateAccountsPayableBillingAddress",
    {
      description: "update accounts payable billing address",
      inputSchema: z.object({
      data: accountsPayableBillingAddressValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsPayableBillingAddress(ctx.client, ctx.companyId, params.data, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsPayableBillingAddress"),
  );

  server.registerTool(
    "settings_updateAccountsReceivableBillingAddress",
    {
      description: "update accounts receivable billing address",
      inputSchema: z.object({
      data: accountsReceivableBillingAddressValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsReceivableBillingAddress(ctx.client, ctx.companyId, params.data, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsReceivableBillingAddress"),
  );

  server.registerTool(
    "settings_deleteApiKey",
    {
      description: "delete api key",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteApiKey(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: settings_deleteApiKey"),
  );

  server.registerTool(
    "settings_deleteWebhook",
    {
      description: "delete webhook",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deleteWebhook(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: settings_deleteWebhook"),
  );

  server.registerTool(
    "settings_deactivateWebhooks",
    {
      description: "deactivate webhooks",
      inputSchema: z.object({}),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deactivateWebhooks(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_deactivateWebhooks"),
  );

  server.registerTool(
    "settings_getApiKeys",
    {
      description: "get api keys",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApiKeys(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: settings_getApiKeys"),
  );

  server.registerTool(
    "settings_getCompanies",
    {
      description: "get companies",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompanies(ctx.client, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_getCompanies"),
  );

  server.registerTool(
    "settings_getCompany",
    {
      description: "get company",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompany(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCompany"),
  );

  server.registerTool(
    "settings_getCompanyPlan",
    {
      description: "get company plan",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompanyPlan(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCompanyPlan"),
  );

  server.registerTool(
    "settings_getCompanySettings",
    {
      description: "get company settings",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompanySettings(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCompanySettings"),
  );

  server.registerTool(
    "settings_getCompanyIntegrations",
    {
      description: "get company integrations",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCompanyIntegrations(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCompanyIntegrations"),
  );

  server.registerTool(
    "settings_getConfig",
    {
      description: "get config",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getConfig(ctx.client);
      return toMcpResult(result);
    }, "Failed: settings_getConfig"),
  );

  server.registerTool(
    "settings_getCurrentSequence",
    {
      description: "get current sequence",
      inputSchema: z.object({
      table: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCurrentSequence(ctx.client, params.table, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCurrentSequence"),
  );

  server.registerTool(
    "settings_getCustomField",
    {
      description: "get custom field",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomField(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: settings_getCustomField"),
  );

  server.registerTool(
    "settings_getCustomFields",
    {
      description: "get custom fields",
      inputSchema: z.object({
      table: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomFields(ctx.client, params.table, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getCustomFields"),
  );

  server.registerTool(
    "settings_getCustomFieldsTables",
    {
      description: "get custom fields tables",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomFieldsTables(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: settings_getCustomFieldsTables"),
  );

  server.registerTool(
    "settings_getIntegration",
    {
      description: "get integration",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIntegration(ctx.client, params.id, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getIntegration"),
  );

  server.registerTool(
    "settings_getIntegrations",
    {
      description: "get integrations",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getIntegrations(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getIntegrations"),
  );

  server.registerTool(
    "settings_getKanbanOutputSetting",
    {
      description: "get kanban output setting",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getKanbanOutputSetting(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getKanbanOutputSetting"),
  );

  server.registerTool(
    "settings_getPlanById",
    {
      description: "get plan by id",
      inputSchema: z.object({
      planId: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPlanById(ctx.client, params.planId);
      return toMcpResult(result);
    }, "Failed: settings_getPlanById"),
  );

  server.registerTool(
    "settings_getPlans",
    {
      description: "get plans",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPlans(ctx.client);
      return toMcpResult(result);
    }, "Failed: settings_getPlans"),
  );

  server.registerTool(
    "settings_getNextSequence",
    {
      description: "get next sequence",
      inputSchema: z.object({
      table: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getNextSequence(ctx.client, params.table, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getNextSequence"),
  );

  server.registerTool(
    "settings_getSequence",
    {
      description: "get sequence",
      inputSchema: z.object({
      table: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSequence(ctx.client, params.table, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getSequence"),
  );

  server.registerTool(
    "settings_getSequences",
    {
      description: "get sequences",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSequences(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: settings_getSequences"),
  );

  server.registerTool(
    "settings_getSequencesList",
    {
      description: "get sequences list",
      inputSchema: z.object({
      table: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSequencesList(ctx.client, params.table, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getSequencesList"),
  );

  server.registerTool(
    "settings_getTerms",
    {
      description: "get terms",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getTerms(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: settings_getTerms"),
  );

  server.registerTool(
    "settings_getWebhook",
    {
      description: "get webhook",
      inputSchema: z.object({
      id: z.string(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWebhook(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: settings_getWebhook"),
  );

  server.registerTool(
    "settings_getWebhookTables",
    {
      description: "get webhook tables",
      inputSchema: z.object({}),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWebhookTables(ctx.client);
      return toMcpResult(result);
    }, "Failed: settings_getWebhookTables"),
  );

  server.registerTool(
    "settings_getWebhooks",
    {
      description: "get webhooks",
      inputSchema: z.object({
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().nullable()
  }).optional(),
    }),
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getWebhooks(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: settings_getWebhooks"),
  );

  server.registerTool(
    "settings_insertCompany",
    {
      description: "insert company",
      inputSchema: z.object({
      company: companyValidator,
      ownerId: z.string().optional(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await insertCompany(ctx.client, params.company, params.ownerId);
      return toMcpResult(result);
    }, "Failed: settings_insertCompany"),
  );

  server.registerTool(
    "settings_updateCompanyPlan",
    {
      description: "update company plan",
      inputSchema: z.object({
      data: z.object({
    stripeCustomerId: z.string(),
    stripeSubscriptionId: z.string(),
    stripeSubscriptionStatus: z.string(),
    subscriptionStartDate: z.string()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCompanyPlan(ctx.client, { ...params.data, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: settings_updateCompanyPlan"),
  );

  server.registerTool(
    "settings_seedCompany",
    {
      description: "seed company",
      inputSchema: z.object({}),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await seedCompany(ctx.client, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_seedCompany"),
  );

  server.registerTool(
    "settings_updateCompany",
    {
      description: "update company",
      inputSchema: z.object({
      company: companyValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateCompany(ctx.client, ctx.companyId, { ...params.company, updatedBy: ctx.userId, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: settings_updateCompany"),
  );

  server.registerTool(
    "settings_updateKanbanOutputSetting",
    {
      description: "update kanban output setting",
      inputSchema: z.object({
      kanbanOutput: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateKanbanOutputSetting(ctx.client, ctx.companyId, params.kanbanOutput);
      return toMcpResult(result);
    }, "Failed: settings_updateKanbanOutputSetting"),
  );

  server.registerTool(
    "settings_updateMetricSettings",
    {
      description: "update metric settings",
      inputSchema: z.object({
      useMetric: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMetricSettings(ctx.client, ctx.companyId, params.useMetric);
      return toMcpResult(result);
    }, "Failed: settings_updateMetricSettings"),
  );

  server.registerTool(
    "settings_upsertApiKey",
    {
      description: "upsert api key",
      inputSchema: z.object({
      apiKey: apiKeyValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertApiKey(ctx.client, { ...params.apiKey, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: settings_upsertApiKey"),
  );

  server.registerTool(
    "settings_updateDigitalQuoteSetting",
    {
      description: "update digital quote setting",
      inputSchema: z.object({
      digitalQuoteEnabled: z.boolean(),
      digitalQuoteNotificationGroup: z.array(z.string()),
      digitalQuoteIncludesPurchaseOrders: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDigitalQuoteSetting(ctx.client, ctx.companyId, params.digitalQuoteEnabled, params.digitalQuoteNotificationGroup, params.digitalQuoteIncludesPurchaseOrders);
      return toMcpResult(result);
    }, "Failed: settings_updateDigitalQuoteSetting"),
  );

  server.registerTool(
    "settings_updateLogoDark",
    {
      description: "update logo dark",
      inputSchema: z.object({
      logoDark: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateLogoDark(ctx.client, ctx.companyId, params.logoDark);
      return toMcpResult(result);
    }, "Failed: settings_updateLogoDark"),
  );

  server.registerTool(
    "settings_updateLogoLight",
    {
      description: "update logo light",
      inputSchema: z.object({
      logoLight: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateLogoLight(ctx.client, ctx.companyId, params.logoLight);
      return toMcpResult(result);
    }, "Failed: settings_updateLogoLight"),
  );

  server.registerTool(
    "settings_updateLogoDarkIcon",
    {
      description: "update logo dark icon",
      inputSchema: z.object({
      logoDarkIcon: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateLogoDarkIcon(ctx.client, ctx.companyId, params.logoDarkIcon);
      return toMcpResult(result);
    }, "Failed: settings_updateLogoDarkIcon"),
  );

  server.registerTool(
    "settings_updateLogoLightIcon",
    {
      description: "update logo light icon",
      inputSchema: z.object({
      logoLightIcon: z.string().nullable(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateLogoLightIcon(ctx.client, ctx.companyId, params.logoLightIcon);
      return toMcpResult(result);
    }, "Failed: settings_updateLogoLightIcon"),
  );

  server.registerTool(
    "settings_updateMaterialGeneratedIdsSetting",
    {
      description: "update material generated ids setting",
      inputSchema: z.object({
      materialGeneratedIds: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMaterialGeneratedIdsSetting(ctx.client, ctx.companyId, params.materialGeneratedIds);
      return toMcpResult(result);
    }, "Failed: settings_updateMaterialGeneratedIdsSetting"),
  );

  server.registerTool(
    "settings_updateMaterialUnitsSetting",
    {
      description: "update material units setting",
      inputSchema: z.object({
      useMetric: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMaterialUnitsSetting(ctx.client, ctx.companyId, params.useMetric);
      return toMcpResult(result);
    }, "Failed: settings_updateMaterialUnitsSetting"),
  );

  server.registerTool(
    "settings_updateProductLabelSize",
    {
      description: "update product label size",
      inputSchema: z.object({
      productLabelSize: z.string(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateProductLabelSize(ctx.client, ctx.companyId, params.productLabelSize);
      return toMcpResult(result);
    }, "Failed: settings_updateProductLabelSize"),
  );

  server.registerTool(
    "settings_updatePurchasingPdfThumbnails",
    {
      description: "update purchasing pdf thumbnails",
      inputSchema: z.object({
      includeThumbnailsOnPurchasingPdfs: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchasingPdfThumbnails(ctx.client, ctx.companyId, params.includeThumbnailsOnPurchasingPdfs);
      return toMcpResult(result);
    }, "Failed: settings_updatePurchasingPdfThumbnails"),
  );

  server.registerTool(
    "settings_updateSalesPdfThumbnails",
    {
      description: "update sales pdf thumbnails",
      inputSchema: z.object({
      includeThumbnailsOnSalesPdfs: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSalesPdfThumbnails(ctx.client, ctx.companyId, params.includeThumbnailsOnSalesPdfs);
      return toMcpResult(result);
    }, "Failed: settings_updateSalesPdfThumbnails"),
  );

  server.registerTool(
    "settings_updateJobTravelerWorkInstructions",
    {
      description: "update job traveler work instructions",
      inputSchema: z.object({
      jobTravelerIncludeWorkInstructions: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateJobTravelerWorkInstructions(ctx.client, ctx.companyId, params.jobTravelerIncludeWorkInstructions);
      return toMcpResult(result);
    }, "Failed: settings_updateJobTravelerWorkInstructions"),
  );

  server.registerTool(
    "settings_updateTimeCardSetting",
    {
      description: "update time card setting",
      inputSchema: z.object({
      timeCardEnabled: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateTimeCardSetting(ctx.client, ctx.companyId, params.timeCardEnabled);
      return toMcpResult(result);
    }, "Failed: settings_updateTimeCardSetting"),
  );

  server.registerTool(
    "settings_updateConsoleSetting",
    {
      description: "update console setting",
      inputSchema: z.object({
      consoleEnabled: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateConsoleSetting(ctx.client, ctx.companyId, params.consoleEnabled, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_updateConsoleSetting"),
  );

  server.registerTool(
    "settings_updateRfqReadySetting",
    {
      description: "update rfq ready setting",
      inputSchema: z.object({
      rfqReadyNotificationGroup: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateRfqReadySetting(ctx.client, ctx.companyId, params.rfqReadyNotificationGroup);
      return toMcpResult(result);
    }, "Failed: settings_updateRfqReadySetting"),
  );

  server.registerTool(
    "settings_updateSuggestionNotificationSetting",
    {
      description: "update suggestion notification setting",
      inputSchema: z.object({
      suggestionNotificationGroup: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSuggestionNotificationSetting(ctx.client, ctx.companyId, params.suggestionNotificationGroup);
      return toMcpResult(result);
    }, "Failed: settings_updateSuggestionNotificationSetting"),
  );

  server.registerTool(
    "settings_updateMaintenanceDispatchNotificationSettings",
    {
      description: "update maintenance dispatch notification settings",
      inputSchema: z.object({
      settings: z.object({
    maintenanceDispatchNotificationGroup: z.array(z.string()).optional(),
    qualityDispatchNotificationGroup: z.array(z.string()).optional(),
    operationsDispatchNotificationGroup: z.array(z.string()).optional(),
    otherDispatchNotificationGroup: z.array(z.string()).optional()
  }),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateMaintenanceDispatchNotificationSettings(ctx.client, ctx.companyId, params.settings);
      return toMcpResult(result);
    }, "Failed: settings_updateMaintenanceDispatchNotificationSettings"),
  );

  server.registerTool(
    "settings_updateSupplierQuoteNotificationSetting",
    {
      description: "update supplier quote notification setting",
      inputSchema: z.object({
      supplierQuoteNotificationGroup: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierQuoteNotificationSetting(ctx.client, ctx.companyId, params.supplierQuoteNotificationGroup);
      return toMcpResult(result);
    }, "Failed: settings_updateSupplierQuoteNotificationSetting"),
  );

  server.registerTool(
    "settings_updatePurchasePriceUpdateTimingSetting",
    {
      description: "update purchase price update timing setting",
      inputSchema: z.object({
      purchasePriceUpdateTiming: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePurchasePriceUpdateTimingSetting(ctx.client, ctx.companyId, params.purchasePriceUpdateTiming);
      return toMcpResult(result);
    }, "Failed: settings_updatePurchasePriceUpdateTimingSetting"),
  );

  server.registerTool(
    "settings_updateLeadTimesOnReceiptSetting",
    {
      description: "update lead times on receipt setting",
      inputSchema: z.object({
      updateLeadTimesOnReceipt: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateLeadTimesOnReceiptSetting(ctx.client, ctx.companyId, params.updateLeadTimesOnReceipt);
      return toMcpResult(result);
    }, "Failed: settings_updateLeadTimesOnReceiptSetting"),
  );

  server.registerTool(
    "settings_updateSupplierApprovalSetting",
    {
      description: "update supplier approval setting",
      inputSchema: z.object({
      supplierApproval: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSupplierApprovalSetting(ctx.client, ctx.companyId, params.supplierApproval);
      return toMcpResult(result);
    }, "Failed: settings_updateSupplierApprovalSetting"),
  );

  server.registerTool(
    "settings_updateAccountsPayableAddressSetting",
    {
      description: "update accounts payable address setting",
      inputSchema: z.object({
      accountsPayableAddress: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsPayableAddressSetting(ctx.client, ctx.companyId, params.accountsPayableAddress);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsPayableAddressSetting"),
  );

  server.registerTool(
    "settings_updateAccountsReceivableAddressSetting",
    {
      description: "update accounts receivable address setting",
      inputSchema: z.object({
      accountsReceivableAddress: z.boolean(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsReceivableAddressSetting(ctx.client, ctx.companyId, params.accountsReceivableAddress);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsReceivableAddressSetting"),
  );

  server.registerTool(
    "settings_updateAccountsPayableEmail",
    {
      description: "update accounts payable email",
      inputSchema: z.object({
      accountsPayableEmail: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsPayableEmail(ctx.client, ctx.companyId, params.accountsPayableEmail);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsPayableEmail"),
  );

  server.registerTool(
    "settings_updateAccountsReceivableEmail",
    {
      description: "update accounts receivable email",
      inputSchema: z.object({
      accountsReceivableEmail: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateAccountsReceivableEmail(ctx.client, ctx.companyId, params.accountsReceivableEmail);
      return toMcpResult(result);
    }, "Failed: settings_updateAccountsReceivableEmail"),
  );

  server.registerTool(
    "settings_updateDefaultSupplierCc",
    {
      description: "update default supplier cc",
      inputSchema: z.object({
      defaultSupplierCc: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultSupplierCc(ctx.client, ctx.companyId, params.defaultSupplierCc);
      return toMcpResult(result);
    }, "Failed: settings_updateDefaultSupplierCc"),
  );

  server.registerTool(
    "settings_updateDefaultCustomerCc",
    {
      description: "update default customer cc",
      inputSchema: z.object({
      defaultCustomerCc: z.array(z.string()),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateDefaultCustomerCc(ctx.client, ctx.companyId, params.defaultCustomerCc);
      return toMcpResult(result);
    }, "Failed: settings_updateDefaultCustomerCc"),
  );

  server.registerTool(
    "settings_updateQuoteLineCategoryMarkups",
    {
      description: "update quote line category markups",
      inputSchema: z.object({
      quoteLineCategoryMarkups: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateQuoteLineCategoryMarkups(ctx.client, ctx.companyId, params.quoteLineCategoryMarkups);
      return toMcpResult(result);
    }, "Failed: settings_updateQuoteLineCategoryMarkups"),
  );

  server.registerTool(
    "settings_updateSequence",
    {
      description: "update sequence",
      inputSchema: z.object({
      table: z.string(),
      sequence: sequenceValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateSequence(ctx.client, params.table, ctx.companyId, { ...params.sequence, updatedBy: ctx.userId, companyId: ctx.companyId });
      return toMcpResult(result);
    }, "Failed: settings_updateSequence"),
  );

  server.registerTool(
    "settings_updateIntegrationMetadata",
    {
      description: "update integration metadata",
      inputSchema: z.object({
      integrationId: z.string(),
      metadata: z.any(),
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updateIntegrationMetadata(ctx.client, ctx.companyId, params.integrationId, params.metadata, ctx.userId);
      return toMcpResult(result);
    }, "Failed: settings_updateIntegrationMetadata"),
  );

  server.registerTool(
    "settings_upsertWebhook",
    {
      description: "upsert webhook",
      inputSchema: z.object({
      webhook: webhookValidator,
    }),
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertWebhook(ctx.client, { ...params.webhook, companyId: ctx.companyId, createdBy: ctx.userId });
      return toMcpResult(result);
    }, "Failed: settings_upsertWebhook"),
  );
};
