import {
  Document,
  Font,
  Page,
  StyleSheet,
  Text,
  View
} from "@react-pdf/renderer";
import { themes } from "../../../utils/src/themes";
import type { Company } from "../types";
import ExportTemplateTable, {
  type ExportField,
  type ExportRow,
  type TableStyleConfig
} from "./components/ExportTemplateTable";
import Footer from "./components/Footer";

export type { ExportField, ExportRow };

const MARGIN_PADDING: Record<string, string> = {
  default: "20px 40px 50px 40px",
  narrow: "15px 25px 45px 25px",
  wide: "20px 60px 50px 60px"
};

export type ExportTemplateConfig = {
  templateStyle: string;
  colorTheme: string;
  templateFont: string;
  margins: string;
  fontSize: string;
  pdfTitleConfigs: {
    title: string;
    isUppercase: boolean;
    layout: string;
  };
  pageFooterConfigs: {
    enablePageNumber: boolean;
    enableGeneratedBy: boolean;
    enableTimeStamp: boolean;
  };
};

export interface ExportTemplatePDFProps {
  rows: ExportRow[];
  fields: ExportField[];
  config: ExportTemplateConfig;
  company: Company;
  locale: string;
  currencyCode?: string;
  templateName?: string;
  generatedBy?: string;
}

const ExportTemplatePDF = ({
  rows,
  fields,
  config,
  company,
  locale,
  currencyCode,
  templateName,
  generatedBy
}: ExportTemplatePDFProps) => {
  // Register font
  const fontFamily = config.templateFont;
  Font.register({
    family: "Inter",
    fonts: [
      {
        src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf"
      },
      {
        src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf",
        fontWeight: 300
      },
      {
        src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf",
        fontWeight: 500
      },
      {
        src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
        fontWeight: 700
      },
      {
        src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf",
        fontWeight: 900
      }
    ]
  });

  const resolvedFont = fontFamily;
  const colorTheme = themes.find((theme) => theme.name === config.colorTheme);
  const headerBg = `hsl(${colorTheme?.activeColor.light})`;
  const padding = MARGIN_PADDING[config.margins] ?? MARGIN_PADDING.default;
  const isModern = config.templateStyle === "REPORT_TEMPLATE_MODERN";
  const isMinimal = config.templateStyle === "REPORT_TEMPLATE_MINIMAL";

  const tableStyle: TableStyleConfig = {
    headerBg: isMinimal ? "#f3f4f6" : `hsl(${colorTheme?.activeColor.light})`,
    headerText: isMinimal ? "#374151" : "#ffffff",
    evenRowBg: "#ffffff",
    oddRowBg: isMinimal ? "#ffffff" : "#f9fafb",
    borderColor: "#e5e7eb",
    showBorders: !isMinimal,
    fontSize: config.fontSize
  };

  const rawTitle =
    config.pdfTitleConfigs.title || templateName || "Export Report";
  const displayTitle = config.pdfTitleConfigs.isUppercase
    ? rawTitle.toUpperCase()
    : rawTitle;
  const titleAlign =
    config.pdfTitleConfigs.layout === "centered"
      ? "center"
      : config.pdfTitleConfigs.layout === "right_aligned"
        ? "right"
        : "left";

  const styles = StyleSheet.create({
    page: {
      fontFamily: resolvedFont,
      padding,
      color: "#000000",
      backgroundColor: "#FFFFFF"
    },
    accentBar: {
      height: 4,
      backgroundColor: headerBg,
      marginBottom: 12
    },
    titleSection: {
      marginBottom: 14
    },
    companyName: {
      fontSize: 9,
      color: "#6b7280",
      textAlign: titleAlign,
      marginBottom: 4
    },
    title: {
      fontSize: 16,
      fontWeight: 700,
      textAlign: titleAlign,
      color: headerBg,
      marginBottom: 2
    },
    subtitle: {
      fontSize: 8,
      color: "#9ca3af",
      textAlign: titleAlign
    },
    divider: {
      height: 1,
      backgroundColor: "#e5e7eb",
      marginBottom: 10
    },
    emptyState: {
      fontSize: 10,
      color: "#9ca3af",
      textAlign: "center",
      marginTop: 40
    }
  });

  const generatedAt = new Intl.DateTimeFormat(locale, {
    dateStyle: "long",
    ...(config.pageFooterConfigs.enableTimeStamp ? { timeStyle: "short" } : {})
  }).format(new Date());

  const footerLabel = config.pageFooterConfigs.enableGeneratedBy
    ? `Generated by ${generatedBy ?? company.name}`
    : undefined;

  const showFooter =
    config.pageFooterConfigs.enablePageNumber ||
    config.pageFooterConfigs.enableGeneratedBy;

  return (
    <Document
      title={displayTitle}
      author={company.name ?? "Carbon"}
      subject={rawTitle}
    >
      <Page size="A4" orientation="landscape" style={styles.page}>
        {isModern && <View style={styles.accentBar} />}

        <View style={styles.titleSection}>
          <Text style={styles.companyName}>{company.name}</Text>
          <Text style={styles.title}>{displayTitle}</Text>
          <Text style={styles.subtitle}>{generatedAt}</Text>
        </View>

        <View style={styles.divider} />

        {rows.length > 0 ? (
          <ExportTemplateTable
            fields={fields}
            rows={rows}
            style={tableStyle}
            locale={locale}
            currencyCode={currencyCode}
          />
        ) : (
          <Text style={styles.emptyState}>No data found</Text>
        )}

        {showFooter && <Footer label={footerLabel} />}
      </Page>
    </Document>
  );
};

export default ExportTemplatePDF;
